/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 rob.glb --transform 
Files: rob.glb [27.3MB] > D:\MernStack\3\3drobo\public\rob-transformed.glb [3.76MB] (86%)
Author: OSCAR CREATIVO (https://sketchfab.com/oscar_creativo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-character-bot-blast-r-325-by-oscar-creativo-7c3843d203aa4044ae38f7a74645b345
Title: FREE CHARACTER BOT BLAST R-325 BY Oscar CREATIVO
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene } = useGLTF('/rob-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials, animations } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.BOT_BLAST_1002} skeleton={nodes.Object_7.skeleton} morphTargetDictionary={nodes.Object_7.morphTargetDictionary} morphTargetInfluences={nodes.Object_7.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.016} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.BOT_BLAST_1005} skeleton={nodes.Object_9.skeleton} morphTargetDictionary={nodes.Object_9.morphTargetDictionary} morphTargetInfluences={nodes.Object_9.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.016} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.BOT_BLAST_1006} skeleton={nodes.Object_11.skeleton} morphTargetDictionary={nodes.Object_11.morphTargetDictionary} morphTargetInfluences={nodes.Object_11.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.016} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.BOT_BLAST_1004} skeleton={nodes.Object_13.skeleton} morphTargetDictionary={nodes.Object_13.morphTargetDictionary} morphTargetInfluences={nodes.Object_13.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.016} />
        <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.BOT_BLAST_1003} skeleton={nodes.Object_15.skeleton} morphTargetDictionary={nodes.Object_15.morphTargetDictionary} morphTargetInfluences={nodes.Object_15.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.016} />
        <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.BOT_BLAST_1001} skeleton={nodes.Object_17.skeleton} morphTargetDictionary={nodes.Object_17.morphTargetDictionary} morphTargetInfluences={nodes.Object_17.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.016} />
      </group>
    </group>
  )
}

useGLTF.preload('/rob-transformed.glb')
